{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ecommerce-app.namespace" . }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
{{- end }}
