{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-db-secret
  namespace: {{ include "ecommerce-app.namespace" . }}
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASS: {{ .Values.secret.dbPass | quote }}
{{- end }}
